{{ if ne .Values.environments.UNLEASH_API_TOKEN "" }}
apiVersion: v1
kind: Secret
metadata:
  name: unleash-api-token
  labels:
      {{- include "unleash-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  UNLEASH_API_TOKEN: {{ default "" .Values.environments.UNLEASH_API_TOKEN | b64enc | quote }}
{{- end }}